version: '3.3'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    
  pitakapi: 
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql
